### PR TITLE
Handle negative time.sleep values

### LINKED ISSUE #5895: time.sleep(-1.0) causes panic
## Summary
https://github.com/RustPython/RustPython/pull/5892/files#r2183174081
```
import time
time.sleep(-1)
```

## Expected
raise exception

## Actual
panic

### PR DESCRIPTION
**Pull request by ever0de**
resolved #5895

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved validation to prevent negative durations when converting from Python objects, ensuring that negative values now raise clear errors.

* **New Features**
  * Enhanced error messaging for invalid sleep durations, providing a more user-friendly message when a negative duration is specified.

* **Refactor**
  * Updated the `sleep` function to accept a wider range of Python objects for specifying sleep duration, increasing flexibility in usage.
  * Unified and simplified platform-specific sleep handling for better consistency across environments.

### CODE REVIEW

File: vm/src/stdlib/time.rs [hunk 1]
```diff
@@ -90,8 +90,20 @@ mod decl {
...
+        let dur = seconds.try_into_value::<Duration>(vm).map_err(|e| {
+            if e.class().is(vm.ctx.exceptions.value_error) {
+                if let Some(s) = e.args().first().and_then(|arg| arg.str(vm).ok()) {
+                    if s.as_str() == "negative duration" {
+                        return vm.new_value_error("sleep length must be non-negative");
+                    }
+                }
+            }
+            e
+        })?;
```
Comment (youknowone) [inline vm/src/stdlib/time.rs:102]: Now the two sleep functions share the same error handling.
Originally, the reason they were split was because they didn’t share any logic, so keeping them separate was simpler.
But that’s no longer the case.
Let’s remove #[cfg(not(unix))] from this function and make it the sole function responsible for validating the parameters of sleep.
We should move the cfg checks to the actual implementation instead.

File: vm/src/stdlib/time.rs [hunk 2]
```diff
@@ -691,8 +703,17 @@ mod platform {
     }
 
     #[pyfunction]
-    fn sleep(dur: Duration, vm: &VirtualMachine) -> PyResult<()> {
-        // this is basically std::thread::sleep, but that catches interrupts and we don't want to;
```
Comment (youknowone) [inline vm/src/stdlib/time.rs:695]: This comment is not expected to be removed

File: vm/src/stdlib/time.rs (hunk 1 above)
Comment (ever0de) [reply vm/src/stdlib/time.rs:102]: [Currently](https://github.com/RustPython/RustPython/pull/5906/commits/72d612c3ee4159ac3747af26f88fc3fe83770075), the sleep function is implemented directly in the `decl` module with cfg blocks for platform-specific implementations:

```rust
#[pyfunction]
fn sleep(seconds: PyObjectRef, vm: &VirtualMachine) -> PyResult<()> {
    let dur = seconds.try_into_value::<Duration>(vm).map_err(..)?;

    #[cfg(unix)]
    {
        // Unix-specific nanosleep implementation
    }
    #[cfg(not(unix))]
    {
        // std::thread::sleep for other platforms
    }
}
```

Other functions pattern:
```rust
// decl module
#[pyfunction]
fn monotonic(vm: &VirtualMachine) -> PyResult<f64> {
    Ok(get_monotonic_time(vm)?.as_secs_f64())
}

// platform module  
pub(super) fn get_monotonic_time(vm: &VirtualMachine) -> PyResult<Duration> {
    // Platform-specific implementation
}
```

Should we refactor `sleep` to follow the platform pattern for consistency, or it's not necessary since `sleep` isn't reused and would only involve simple wrapping?

Comment (youknowone) [reply vm/src/stdlib/time.rs:102]: either way okay

**Review by youknowone — APPROVED** [review]
Thank you for contributing!
