### PR TITLE
Fixes that `id()` of `tuple` was changing on `* 1`

### LINKED ISSUE #2840: `id(a) != id(a * 1)` for `tuple`, str and bytes
## Feature

CPython:

```python
>>> a = (1, 2)
>>> id(a), id(a * 1)
(4379030656, 4379030656)
```

RustPython:

```
>>>>> a = (1, 2)
>>>>> id(a), id(a * 1)
(140352989490368, 140352989503168)
```

This is also covered by `seq_tests.test_repeat` which is now marked as `unittest.expectedFailure`.

### PR DESCRIPTION
**Pull request by sobolevn**
Refs #2840

Reference: https://github.com/python/cpython/blob/c0ab59f7de1906feee21c057ad433fad924d1e38/Objects/tupleobject.c#L560-L567

### CODE REVIEW

File: vm/src/builtins/tuple.rs [hunk 1]
```diff
@@ -169,11 +169,17 @@ impl PyTuple {
 
     #[pymethod(name = "__mul__")]
     #[pymethod(name = "__rmul__")]
-    fn mul(&self, counter: isize, vm: &VirtualMachine) -> PyRef<Self> {
-        if self.elements.is_empty() || counter == 0 {
+    fn mul(zelf: PyRef<Self>, counter: isize, vm: &VirtualMachine) -> PyRef<Self> {
+        if zelf.elements.is_empty() || counter == 0 {
             vm.ctx.empty_tuple.clone()
+        } else if counter == 1 && zelf.clone_class().is(PyTuple::class(vm)) {
```
Comment (DimitrisJim) [inline vm/src/builtins/tuple.rs:175]: No need to clone here:

```suggestion
        } else if counter == 1 && zelf.class().is(&vm.ctx.types.tuple_type) {
```
