### PR TITLE
Fix eval doesn't work correctly

### LINKED ISSUE #4364: `eval` doesn't work correctly.
On CPython, `eval` works even if space exists at the beginning of the line.

```
>>> eval("   1")
1
```

But on RustPython, IndentationError occurs.

```
>>>>> eval("   1")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndentationError: unexpected indent at line 1 column 4
   1
   ^
```

### PR DESCRIPTION
**Pull request by branai**
Solved by removing preceding whitespaces, tabs, and newlines for evals only. Fixes #4364

### CODE REVIEW

File: vm/src/stdlib/builtins.rs [hunk 1]
```diff
@@ -256,6 +256,15 @@ mod builtins {
                     ));
                 }
 
+                // Check for newlines, tabs, or whitespaces at start
```
Comment (DimitrisJim) [inline vm/src/stdlib/builtins.rs:259]: Thanks! Though there's not really a need to manually remove them, you can use `trim_start()` on source before we create the `PyStr` from it, i.e `vm.ctx.new_str(source.trim_start())`.

Note that CPython currently ignores tabs and spaces only, don't think this is really an issue since the lexer ignores those either way.

**Comment by branai** [comment]
@DimitrisJim I changed it to what you suggested, thank you for your help!

**Comment by DimitrisJim** [comment]
There's a couple of tests passing in `test_string_literals.py` that you need to tweak. `test_eval_bytes_normal`, `test_eval_bytes_raw`, `test_eval_str_normal`, `test_eval_str_raw`, `test_eval_str_u` all now succeed. You should open that file and remove the decorators on them, i.e remove the lines:

```python
# TODO: RUSTPYTHON
@unittest.expectedFailure
```

and then the tests should pass just fine.

**Review by DimitrisJim — APPROVED** [review]
Great, thanks!
