### PR TITLE
Fixing assert second argument formatting

### LINKED ISSUE #389: Panic if second argument to assert isn't a string.
```
>>>>> assert 1 == 0, 9
Traceback (most recent call last):
  File <unknown>, line 1, in <module>
thread 'main' panicked at 'Inner error getting str', vm/src/obj/objstr.rs:105:9
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

### PR DESCRIPTION
**Pull request by veera83372**
Fixes #389

### CODE REVIEW

File: vm/src/exceptions.rs [hunk 1]
```diff
@@ -71,7 +71,10 @@ fn exception_str(vm: &mut VirtualMachine, args: PyFuncArgs) -> PyResult {
     );
     let type_name = objtype::get_type_name(&exc.typ());
     let msg = if let Some(m) = exc.get_attr("msg") {
-        objstr::get_value(&m)
+        match vm.to_pystr(&m) {
+            Ok(msg) => msg,
+            _ => "".to_string(),
```
Comment (cthulahoops) [inline vm/src/exceptions.rs]: In this case it looks like we want the string ```"<exception str() failed>"```:

```
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    assert False, Foo()
AssertionError: <exception str() failed>
```

Comment (veera83372) [reply vm/src/exceptions.rs]: I don't think I got it correctly but I am assuming instead of `""` we need 
`"<exception str() failed>"`

Let me know if that is the case

Comment (cthulahoops) [reply vm/src/exceptions.rs]: Yes, exactly.

Comment (veera83372) [reply vm/src/exceptions.rs]: Done
