### PR TITLE
typing upgrade to 3.13.2

### LINKED ISSUE #5584: AttributeError when using pip==25.0.1
## Summary

Building `rustpython@7fea1e1`, installing `pip` with `ensurepip`, then upgrading `pip` to 25.0.1 produces the following stack trace when running `pip`:

```
$ rustpython -m pip
Traceback (most recent call last):
  File "/home/user/.cargo/git/checkouts/rustpython-63090cdce5e18442/7fea1e1/pylib/Lib/runpy.py", line 197, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/user/.cargo/git/checkouts/rustpython-63090cdce5e18442/7fea1e1/pylib/Lib/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/user/.local/lib/rustpython3.13/site-packages/pip/__main__.py", line 22, in <module>
    from pip._internal.cli.main import main as _main
  File "/home/user/.local/lib/rustpython3.13/site-packages/pip/_internal/cli/main.py", line 11, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/home/user/.local/lib/rustpython3.13/site-packages/pip/_internal/cli/autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/home/user/.local/lib/rustpython3.13/site-packages/pip/_internal/cli/main_parser.py", line 9, in <module>
    from pip._internal.build_env import get_runnable_pip
  File "/home/user/.local/lib/rustpython3.13/site-packages/pip/_internal/build_env.py", line 17, in <module>
    from pip._internal.cli.spinners import open_spinner
  File "/home/user/.local/lib/rustpython3.13/site-packages/pip/_internal/cli/spinners.py", line 9, in <module>
    from pip._internal.utils.logging import get_indentation
  File "/home/user/.local/lib/rustpython3.13/site-packages/pip/_internal/utils/logging.py", line 29, in <module>
    from pip._internal.utils.misc import ensure_dir
  File "/home/user/.local/lib/rustpython3.13/site-packages/pip/_internal/utils/misc.py", line 44, in <module>
    from pip._internal.utils.retry import retry
  File "/home/user/.local/lib/rustpython3.13/site-packages/pip/_internal/utils/retry.py", line 5, in <module>
    from pip._vendor.typing_extensions import ParamSpec
  File "/home/user/.local/lib/rustpython3.13/site-packages/pip/_vendor/typing_extensions.py", line 2335, in <module>
    Unpack = typing.Unpack
AttributeError: module 'typing' has no attribute 'Unpack'
```

### PR DESCRIPTION
**Pull request by arihant2math**
Fixes: #5584 #5252
Closes: #4946

### CODE REVIEW

**Comment by youknowone** [comment]
The failing tests are unexpected success. Removing expectedFailure will fix them

**Comment by arihant2math** [comment]
Rebasing has lead to an import error/compiler panic.

**Comment by youknowone** [comment]
That's because `_py_exception_group.py` is recently merged.
It uses those features form typing:

```
from typing import TYPE_CHECKING, Generic, Type, TypeVar, cast, overload
```
Any chance to break one of them?

**Comment by arihant2math** [comment]
hmmm. Blocking on #5622, so I can rewrite that in rust.

**Comment by arihant2math** [comment]
Oh wait I can just break that import statement :D

**Comment by arihant2math** [comment]
Blocked on #5628 so I can atleast partially fix codegen.

**Comment by arihant2math** [comment]
One minor issue ... the pip install needs to be fixed. I can't really replicate on my machine because I'm on windows.

**Comment by youknowone** [comment]
`resolve_mro` fails

```
Traceback (most recent call last):
  File "<stdin>", line 6, in <module>
  File "~/Projects/RustPython/pylib/Lib/runpy.py", line 224, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "~/Projects/RustPython/pylib/Lib/runpy.py", line 94, in _run_module_code
    with _TempModule(mod_name) as temp_module, _ModifiedArgv0(fname):
  File "~/Projects/RustPython/pylib/Lib/runpy.py", line 97, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "~/Projects/RustPython/pylib/Lib/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/var/folders/4l/db5by6f97gl8z692_wckqb3w0000gn/T/tmpp0rarl2n/pip-23.2.1-py3-none-any.whl/pip/__main__.py", line 24, in <module>
  File "/var/folders/4l/db5by6f97gl8z692_wckqb3w0000gn/T/tmpp0rarl2n/pip-23.2.1-py3-none-any.whl/pip/_internal/cli/main.py", line 77, in main
  File "/var/folders/4l/db5by6f97gl8z692_wckqb3w0000gn/T/tmpp0rarl2n/pip-23.2.1-py3-none-any.whl/pip/_internal/commands/__init__.py", line 114, in create_command
  File "~/Projects/RustPython/pylib/Lib/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "_frozen_importlib", line 1382, in _gcd_import
  File "_frozen_importlib", line 1352, in _find_and_load
  File "_frozen_importlib", line 1355, in _find_and_load
  File "_frozen_importlib", line 1329, in _find_and_load_unlocked
  File "_frozen_importlib", line 1326, in _find_and_load_unlocked
  File "_frozen_importlib", line 1326, in _find_and_load_unlocked
  File "_frozen_importlib", line 945, in _load_unlocked
  File "_frozen_importlib", line 943, in _load_unlocked
  File "_frozen_importlib", line 936, in _load_unlocked
  File "_frozen_importlib", line 930, in _load_unlocked
  File "_frozen_importlib_external", line 994, in exec_module
  File "_frozen_importlib", line 488, in _call_with_frames_removed
  File "/var/folders/4l/db5by6f97gl8z692_wckqb3w0000gn/T/tmpp0rarl2n/pip-23.2.1-py3-none-any.whl/pip/_internal/commands/install.py", line 15, in <module>
  File "/var/folders/4l/db5by6f97gl8z692_wckqb3w0000gn/T/tmpp0rarl2n/pip-23.2.1-py3-none-any.whl/pip/_internal/cli/req_command.py", line 26, in <module>
  File "/var/folders/4l/db5by6f97gl8z692_wckqb3w0000gn/T/tmpp0rarl2n/pip-23.2.1-py3-none-any.whl/pip/_internal/operations/prepare.py", line 32, in <module>
  File "/var/folders/4l/db5by6f97gl8z692_wckqb3w0000gn/T/tmpp0rarl2n/pip-23.2.1-py3-none-any.whl/pip/_internal/network/download.py", line 11, in <module>
  File "/var/folders/4l/db5by6f97gl8z692_wckqb3w0000gn/T/tmpp0rarl2n/pip-23.2.1-py3-none-any.whl/pip/_internal/cli/progress_bars.py", line 4, in <module>
  File "/var/folders/4l/db5by6f97gl8z692_wckqb3w0000gn/T/tmpp0rarl2n/pip-23.2.1-py3-none-any.whl/pip/_vendor/rich/progress.py", line 273, in <module>
  File "~/Projects/RustPython/pylib/Lib/_py_abc.py", line 36, in __new__
    cls = super().__new__(mcls, name, bases, namespace, **kwargs)
TypeError: duplicate base class Generic
Traceback (most recent call last):
  File "~/Projects/RustPython/pylib/Lib/runpy.py", line 197, in _run_module_as_main
    "__main__", mod_spec)
  File "~/Projects/RustPython/pylib/Lib/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "~/Projects/RustPython/pylib/Lib/ensurepip/__main__.py", line 5, in <module>
    sys.exit(ensurepip._main())
  File "~/Projects/RustPython/pylib/Lib/ensurepip/__init__.py", line 290, in _main
    default_pip=args.default_pip,
  File "~/Projects/RustPython/pylib/Lib/ensurepip/__init__.py", line 167, in _bootstrap
    with tempfile.TemporaryDirectory() as tmpdir:
  File "~/Projects/RustPython/pylib/Lib/ensurepip/__init__.py", line 200, in _bootstrap
    return _run_pip([*args, *_PACKAGE_NAMES], additional_paths)
  File "~/Projects/RustPython/pylib/Lib/ensurepip/__init__.py", line 101, in _run_pip
    return subprocess.run(cmd, check=True).returncode
  File "~/Projects/RustPython/pylib/Lib/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
  File "~/Projects/RustPython/pylib/Lib/subprocess.py", line 572, in run
    output=stdout, stderr=stderr)
CalledProcessError: (1, ['~/Projects/RustPython/target/debug/rustpython', '-W', 'ignore::DeprecationWarning', '-c', '\nimport runpy\nimport sys\nsys.path = [\'/var/folders/4l/db5by6f97gl8z692_wckqb3w0000gn/T/tmpp0rarl2n/pip-23.2.1-py3-none-any.whl\'] + sys.path\nsys.argv[1:] = [\'install\', \'--no-cache-dir\', \'--no-index\', \'--find-links\', \'/var/folders/4l/db5by6f97gl8z692_wckqb3w0000gn/T/tmpp0rarl2n\', \'--upgrade\', \'pip\']\nrunpy.run_module("pip", run_name="__main__", alter_sys=True)\n'])
```

**Comment by youknowone** [comment]
While creating a class `_ReadContext`, it takes 3 bases:
```
new heap type: _ReadContext
-- start resolve_mro for:AbstractContextManager, Generic, Generic, 
   base: AbstractContextManager
   base: Generic
   base: Generic
```

The class is this one: https://github.com/pypa/pip/blob/24f4600851bbb3d7f22aed0ba6b1e2dcc4973412/src/pip/_vendor/rich/progress.py#L287-L305

**Comment by youknowone** [comment]
Reproducible code
```
import typing
from typing import ContextManager, Generic, TextIO, BinaryIO
_I = typing.TypeVar("_I", TextIO, BinaryIO)
class _ReadContext(ContextManager[_I], Generic[_I]):
    pass
```

**Comment by arihant2math** [comment]
Great, that's fixed.

**Comment by arihant2math** [comment]
Finally, it all works.
Ready for review.

**Comment by arihant2math** [comment]
@youknowone do you mind reviewing please?

File: vm/src/stdlib/typing.rs [hunk 1]
```diff
@@ -77,15 +84,106 @@ pub(crate) mod _typing {
...
+        }
+
+        #[pymethod]
+        fn has_default(&self) -> PyResult<bool> {
+            // TODO: fix
+            if self.evaluate_default.is_some() || self.default_value.is_some() {
+                Ok(true)
+            } else {
+                Ok(false)
+            }
```
Comment (youknowone) [inline vm/src/stdlib/typing.rs:160]:
```suggestion
            // TODO: fix
            Ok(self.evaluate_default.is_some() || self.default_value.is_some())
```

**Review by youknowone — APPROVED** [review]

**Comment by youknowone** [comment]
Even though there are regressions, merging this have benefits to fix pip
