### PR TITLE
Fix unsupported operand type of str problem

### LINKED ISSUE #1365: unsupported operand type of str type make panic
## Feature
```python
a = ''
a['3']
```
unsupported operand type of str type make panic.
I think it should generate only TypeError, not panic.

### Expected Result
```bash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: string indices must be integers
```

### Actual Result
```bash
thread 'main' panicked at 'TypeError: indexing type "" with index [PyObj PyString { value: "3" }] is not supported (yet?)', vm/src/obj/objstr.rs:1575:9
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

### PR DESCRIPTION
**Pull request by HyeockJinKim**
Modify panic! to Err for unsupported operand type of str problem

Fixes #1365

### CODE REVIEW

**Comment by HyeockJinKim** [comment]
@coolreader18 @youknowone cc @corona10
Can I get a review?

File: vm/src/obj/objstr.rs [hunk 1]
```diff
@@ -1572,10 +1572,10 @@ pub fn subscript(vm: &VirtualMachine, value: &str, b: PyObjectRef) -> PyResult {
         let string = value.to_string().get_slice_items(vm, &b)?;
         Ok(vm.new_str(string))
     } else {
-        panic!(
+        Err(vm.new_type_error(format!(
             "TypeError: indexing type {:?} with index {:?} is not supported (yet?)",
```
Comment (coolreader18) [inline vm/src/obj/objstr.rs]: Maybe remove the "yet" here, as it's not really accurate anymore.
