### PR TITLE
Fix set in-place operators with self argument

### LINKED ISSUE #3881: `set` `intersection_update`, `difference_update`, `symmetric_difference_update` should check self is equal to given arg
## Feature
This is also relevant to inplace operations( `iand`, `isub`, `ixor` ). 
CPython checks whether given argument and selfobject are equal and then returns.

* `intersection_update` : If self == arg, returns self.copy()
* `difference_update` : If self == arg, returns self.clear(); Ok(())
* `symmetric_difference_update` : If self == arg, returns self.clear(); Ok(())

At the current implementation, they get a parameter as `SetIterable` which is converted from PyObjectRef before entering each method.
For checking `self == arg`, we should convert it after checking.

## Python Documentation
* https://github.com/python/cpython/blob/3.10/Objects/setobject.c#L1627-L1630
* https://github.com/python/cpython/blob/3.10/Objects/setobject.c#L1410-L1412
* https://github.com/python/cpython/blob/3.10/Objects/setobject.c#L1186-L1189

## Relevant Test Case
* `test_set.py` `test_inplace_on_self`

### PR DESCRIPTION
**Pull request by HueCodes**
Fixes #3881
close #3912
close #4424
close #4708

  When a set performs in-place operations with itself (`s &= s`, `s -= s`, `s ^= s`), the operators now handle the self-reference case correctly:

  - `__iand__`: no-op (intersection with self is unchanged)
  - `__isub__`: clear (difference with self is empty)
  - `__ixor__`: clear (symmetric difference with self is empty)

## Summary by CodeRabbit

* **Bug Fixes**
  * Corrected behavior of in-place set operations (&=, -=, ^=) when a set operates on itself, preventing unintended modifications.

* **Tests**
  * Added test cases validating in-place set operations when operating on the same set instance.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: crates/vm/src/builtins/set.rs [hunk 1]
```diff
@@ -1305,6 +1315,10 @@ impl AnySet {
         obj.fast_isinstance(ctx.types.set_type) || obj.fast_isinstance(ctx.types.frozenset_type)
     }
 
+    fn is_same_object(&self, other: &PyObject) -> bool {
+        self.object.is(other)
+    }
```
Comment (youknowone) [inline crates/vm/src/builtins/set.rs]: We have a mechanism to do this.

`is` is not a method of `PyObject`, but an object of`AsObject`. And PyObject is implementing AsObject through Borrow<PyObject>.

AnySet can do the same thing.
`impl Borrow<PyObject> for AnySet {}`
will enable AsObject for AnySet. Then `set.is_same_object(zelf.as_object())` above can be simply written as `set.is(zelf.as_object())`

**Comment by HueCodes** [comment]
Done.
