### PR TITLE
fix floordiv and divmod by zero for ints and floats

### LINKED ISSUE #345: Division by zero should raise ZeroDivisionError
CPython, consistently with [documentation](https://docs.python.org/3/library/exceptions.html#ZeroDivisionError), raises `ZeroDivisionError` when trying to divide by 0:

```
>>> 5/0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ZeroDivisionError: division by zero
>>> -5/0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ZeroDivisionError: division by zero
>>> 5%0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ZeroDivisionError: integer division or modulo by zero
```

RustPython on the other hand happily returns `inf` on division and panics on modulo:

```
>>>>> 5/0
inf
>>>>> -5/0
-inf
>>>>> 5%0
thread 'main' panicked at 'explicit panic', /home/silmeth/.cargo/registry/src/github.com-1ecc6299db9ec823/num-bigint-0.2.1/src/algorithms.rs:497:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.
zsh: exit 101   cargo run --release
```

I’ll try to make a PR fixing this and #331.

### PR DESCRIPTION
**Pull request by silmeth**
Fixes #345.

### CODE REVIEW

File: vm/src/obj/objint.rs [hunk 1]
```diff
@@ -462,11 +469,20 @@ fn int_divmod(vm: &mut VirtualMachine, args: PyFuncArgs) -> PyResult {
...
+
     if objtype::isinstance(i2, &vm.ctx.int_type()) {
-        let r1 = int_floordiv(vm, args.clone());
-        let r2 = int_mod(vm, args.clone());
-        Ok(vm.ctx.new_tuple(vec![r1.unwrap(), r2.unwrap()]))
+        let v1 = get_value(i);
+        let v2 = get_value(i2);
+
+        if v2 != BigInt::zero() {
+            let (r1, r2) = v1.div_rem(&v2);
```
Comment (windelbouwman) [inline vm/src/obj/objint.rs]: Nice improvement of using this builtin function!
