### PR TITLE
Fixes infinite recursion on `raise e from e`

### LINKED ISSUE #2779: Raising a user-defined class from itself causes interpreter crashing
In the following example, we define a class error, and instance it. When we execute raise e from e, Rust Python crashes.

test.py
```
class Error(Exception):
	pass

e = Error()
raise e from e

```

Actual output:

> Segmentation fault (core dumped)

System:

> Ubuntu 16.04
> Rust Python 0.1.2 interpreter

### PR DESCRIPTION
**Pull request by sobolevn**
Closes #2779

### CODE REVIEW

File: vm/src/exceptions.rs [hunk 1]
```diff
@@ -195,11 +195,16 @@ pub fn write_exception<W: Write>(
...
     if let Some(cause) = exc.cause() {
-        write_exception(output, vm, &cause)?;
-        writeln!(
-            output,
-            "\nThe above exception was the direct cause of the following exception:\n"
-        )?;
+        // This can be a special case: `raise e from e`,
+        // we just ignore it and treat like `raise e`.
+        // So, doing nothing here.
+        if !cause.as_object().is(&exc) {
```
Comment (DimitrisJim) [inline vm/src/exceptions.rs:201]: Though this handles `raise e from e` it still segfaults in other situations:

```
class E(Exception): pass
class D(E): pass

e, d = E(), D()
raise d from e
```

CPython uses a set to help stop the infinite recursion, constantly filling it up with exceptions until it sees them all. Something similar can be done here (a new private function that `write_exception` calls seems better as to not require callers of this public function to supply the set).

**Review by DimitrisJim — CHANGES_REQUESTED** [review]

File: vm/src/exceptions.rs (hunk 1 above)
Comment (sobolevn) [reply vm/src/exceptions.rs]: Good catch! I've refactored this into a `write_exception_recursive` and added several new tests.
Please, take a look 🙂

File: vm/src/exceptions.rs [hunk 2]
```diff
@@ -253,6 +241,39 @@ fn write_traceback_entry<W: Write>(
...
+            write_exception_recursive(output, vm, &cause, seen)?;
+            writeln!(
+                output,
+                "\nThe above exception was the direct cause of the following exception:\n"
+            )?;
+        } else {
+            seen.insert(cause.as_object().get_id());
+        }
+    } else if let Some(context) = exc.context() {
+        write_exception_recursive(output, vm, &context, seen)?;
```
Comment (DimitrisJim) [inline vm/src/exceptions.rs:267]: Pretty sure this *should* spin if `e.__context__ = e`. Checking the set again before recursing, as done with `cause`, should do the trick.

**Review by DimitrisJim — CHANGES_REQUESTED** [review]

File: vm/src/exceptions.rs (hunk 2 above)
Comment (sobolevn) [reply vm/src/exceptions.rs]: Yes, you are right. I was trying to somehow reproduce it, but I didn't think about direct manipulation 🙈 😆 
Fixed!

Comment (DimitrisJim) [reply vm/src/exceptions.rs]: Yeah, Python allows some pretty wild and head-scratching manipulation. I wasn't even sure if a setter was available for `__context__` in RustPython.

File: extra_tests/snippets/builtin_exceptions.py [hunk 3]
```diff
@@ -0,0 +1,151 @@
...
+
+# New case:
+# explicit `__context__` manipulation.
+
+e = MyError('message')
+e.__context__ = e
+
+try:
+    raise e
+except MyError as exc:
```
Comment (DimitrisJim) [inline extra_tests/snippets/builtin_exceptions.py:146]: I think its actually CPython hanging on this (not sure why CPython runs these snippets) probably due to some ciruclar reference clean-up issues? Not really sure. Running this snippet of code with a build of rustpython passes. 

Changing this to `except Exception: pass` should make the check pass.

Comment (sobolevn) [reply extra_tests/snippets/builtin_exceptions.py:146]: Yes, I can confirm that `CPython` hangs, while `RustPython` works fine.
I will research if we need to submit this bug to CPython team.

Is there any way to distinguish `RustPython` from `CPython` in runtime?

Comment (sobolevn) [reply extra_tests/snippets/builtin_exceptions.py:146]: I see `python_implementation`

Comment (sobolevn) [reply extra_tests/snippets/builtin_exceptions.py:147]: @DimitrisJim it is already reported https://bugs.python.org/issue25782

Comment (DimitrisJim) [reply extra_tests/snippets/builtin_exceptions.py:147]: Good find. That issue is slightly different in scope as far as I can tell (not really involving printing the exceptions). Rustpython also hangs on some of the cycles they create but that should be tackled in a different issue.

**Review by DimitrisJim — APPROVED** [review]

**Comment by DimitrisJim** [comment]
Looks good to me, can you rebase the commits to get a cleaner history?

**Comment by sobolevn** [comment]
Sure!

But, you can press "Squash and merge" to merge a single commit into `master`: https://docs.github.com/en/github/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges#squash-and-merge-your-pull-request-commits This way it won't even re-trigget the CI 👍

File: vm/src/exceptions.rs [hunk 4]
```diff
@@ -253,6 +241,48 @@ fn write_traceback_entry<W: Write>(
...
+        if !seen.contains(&context.as_object().get_id()) {
+            write_exception_recursive(output, vm, &context, seen)?;
+            writeln!(
+                output,
+                "\nDuring handling of the above exception, another exception occurred:\n"
+            )?;
+        } else {
+            seen.insert(context.as_object().get_id());
+        }
+    }
```
Comment (youknowone) [inline vm/src/exceptions.rs:281]:
```suggestion
    if let Some((cause_or_context, msg)) = if let Some(cause) = exc.cause() {
        // This can be a special case: `raise e from e`,
        // we just ignore it and treat like `raise e` without any extra steps.
        Some((
            cause,
            "\nThe above exception was the direct cause of the following exception:\n",
        ))
    } else if let Some(context) = exc.context() {
        // This can be a special case:
        //   e = ValueError('e')
        //   e.__context__ = e
        // In this case, we just ignore
        // `__context__` part from going into recursion.
        Some((
            context,
            "\nDuring handling of the above exception, another exception occurred:\n",
        ))
    } else {
        None
    } {
        if !seen.contains(&cause_or_context.as_object().get_id()) {
            write_exception_recursive(output, vm, &cause_or_context, seen)?;
            writeln!(output, "{}", msg)?;
        } else {
            seen.insert(cause_or_context.as_object().get_id());
        }
    }
```

**Review by youknowone — CHANGES_REQUESTED** [review]

**Review by youknowone — APPROVED** [review]
