### PR TITLE
Fix docs.rs build for rustpython-parser

### LINKED ISSUE #4436: docs.rs cannot generate the documentation for rustpython-parser
rustpython-parser 0.2.0 has just been published on crates.io, unfortunately docs.rs appears to be [unable to generate the documentation](https://docs.rs/crate/rustpython-parser/0.2.0). The relevant line in [the log](https://docs.rs/crate/rustpython-parser/0.2.0/builds/718461) appears to be:

> [INFO] [stderr]   thread 'main' panicked at 'running lalrpop failed. Os { code: 30, kind: ReadOnlyFilesystem, message: "Read-only file system" }', build.rs:79:9

Quoting the [docs.rs documentation](https://docs.rs/about/builds#read-only-directories):

> Most of the sandbox is a read-only file system, including the source directory of your crate and its dependencies. If your build.rs generates files that are relevant for documentation, consider writing to the [cargo output directory](https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-crates), passed in the environment variable OUT_DIR.

So the [compiler/parser/build.rs](https://github.com/RustPython/RustPython/blob/main/compiler/parser/build.rs) script should be updated accordingly. I'll try to make a PR :)

### PR DESCRIPTION
**Pull request by not-my-profile**
docs.rs failed to build the documentation of the recently released rustpython-parser 0.2.0 because the build.rs script couldn't write the parser.rs file because docs.rs builds the documentation in a sandbox with a read-only filesystem.

This commit fixes this by writing the parser.rs file to the cargo output directory instead, as recommended by the docs.rs documentation.[1]

Fixes #4436.

[1]: https://docs.rs/about/builds#read-only-directories

### CODE REVIEW

File: compiler/parser/build.rs [hunk 1]
```diff
@@ -68,16 +68,22 @@ fn requires_lalrpop(source: &str, target: &str) -> Option<String> {
...
 
     #[cfg(feature = "lalrpop")]
-    lalrpop::process_root().unwrap_or_else(|e| {
-        println!("cargo:warning={_message}");
-        panic!("running lalrpop failed. {e:?}");
-    });
+    // We are not using lalrpop::process_root() or Configuration::process_current_dir()
+    // because of https://github.com/lalrpop/lalrpop/issues/699.
+    lalrpop::Configuration::new()
+        .use_cargo_dir_conventions()
```
Comment (youknowone) [inline compiler/parser/build.rs:80]: oh, this is the way to do things.

**Review by youknowone — APPROVED** [review]
Thank you!
