### PR TITLE
Fix __class__

### LINKED ISSUE #583: type( ...).__class__ not work
```
class Test:
  pass

type(Test).__class__
```

**current result:**
> TypeError: argument of type <class 'type'> is required for parameter 1 (_typ) (got: <class 'NoneType'>)

**expected result:**

> nothing

### PR DESCRIPTION
**Pull request by skinny121**
Fixes #583

Moves the \_\_class\_\_ property to object, so lookup of it works properly, this matches CPython. Also to make lookup work the property has to have a \_\_set\_\_ method, at this point it always raises an exception.

### CODE REVIEW

File: vm/src/obj/objfunction.rs [hunk 1]
```diff
@@ -83,6 +95,28 @@ fn member_get(vm: &mut VirtualMachine, mut args: PyFuncArgs) -> PyResult {
     }
 }
 
+fn data_get(vm: &mut VirtualMachine, mut args: PyFuncArgs) -> PyResult {
+    match args.shift().get_attr("fget") {
+        Some(function) => vm.invoke(function, args),
+        None => {
+            println!("A");
```
Comment (OddCoincidence) [inline vm/src/obj/objfunction.rs]: Were this line and the `println!("B")` below left in by mistake?

Comment (skinny121) [reply vm/src/obj/objfunction.rs]: Yes :frowning_face:

**Comment by cthulahoops** [comment]
Are member descriptor and data descriptor actually different things or were member descriptors just missing the set (and hence not working correctly in this case)?

File: vm/src/obj/objobject.rs [hunk 2]
```diff
@@ -190,6 +195,19 @@ fn object_init(vm: &mut VirtualMachine, _args: PyFuncArgs) -> PyResult {
     Ok(vm.ctx.none())
 }
 
+fn object_class(_obj: PyObjectRef, owner: PyObjectRef, _vm: &mut VirtualMachine) -> PyObjectRef {
```
Comment (cthulahoops) [inline vm/src/obj/objobject.rs]: Using a new style function here loses the type check on owner. (We need to implement PyClassRef to support that.)

**Comment by skinny121** [comment]
They are different, member descriptors shouldn't have \_\_set\_\_ as the presence of it affects the lookup. 

In CPython:
```python
>>> type(object.__dict__['__class__'])
<class 'getset_descriptor'>
>>> type(type.__dict__['__mro__'])
<class 'member_descriptor'>
```

I'm been thinking of a nicer way to do this in rust, instead of having different new_xxx_descriptor methods, instead a builder, which would statically work out the python type needed.
```rust
vm.new_property()
     .add_getter(...)
     .add_setter(...)
     .build()
```

**Comment by cthulahoops** [comment]
Great.

The builder sounds nice, probably reasonable to add that later and merge this as is.

File: vm/src/obj/objobject.rs (hunk 2 above)
Comment (cthulahoops) [reply vm/src/obj/objobject.rs]: Rather than having to switch back to old style, how about a "TODO: owner should be PyClassRef once that exists"?
