### PR TITLE
Remove PyStr::as_str

### LINKED ISSUE #7196: Replace PyStr::as_str() to PyStr::to_str()
## Summary

to remove unexpected panic

### PR DESCRIPTION
**Pull request by youknowone**
Fix #7196

## Summary by CodeRabbit

* **Improvements**
  * Wide rollout of UTF‑8/WTF‑8 handling across the VM and standard library for safer, binary‑preserving text processing and improved non‑ASCII rendering.
  * Many object reprs and I/O paths now correctly display surrogate and non‑ASCII content.

* **New Features**
  * UTF‑8 string types and VM helpers exposed to APIs for explicit UTF‑8 handling.

* **Bug Fixes**
  * Stricter string extraction yields earlier, clearer errors and reduces lossy conversions.

### CODE REVIEW

File: crates/vm/src/intern.rs [hunk 1]
```diff
@@ -152,10 +152,21 @@ impl CachedPyStrRef {
...
 
+impl PyInterned<PyStr> {
+    /// Returns `&str` for interned strings.
+    #[inline]
+    pub fn as_str(&self) -> &str {
+        self.inner
+            .to_str()
+            .unwrap_or_else(|| panic!("interned str is always valid UTF-8"))
+    }
+}
```
[the remark this answers is not in the document]
Comment (youknowone) [reply crates/vm/src/intern.rs:172]: This is intended for ergonomics. Many PyInterned is guaranteed to be utf8

File: crates/vm/src/builtins/function.rs [hunk 2]
```diff
@@ -1074,28 +1075,6 @@ impl PyBoundMethod {
     fn __module__(&self, vm: &VirtualMachine) -> Option<PyObjectRef> {
         self.function.get_attr("__module__", vm).ok()
     }
-
-    #[pygetset]
-    fn __qualname__(&self, vm: &VirtualMachine) -> PyResult {
```
Comment (ShaharNaveh) [inline crates/vm/src/builtins/function.rs:1079]: Why was this deleted?

File: crates/vm/src/builtins/str.rs [hunk 3]
```diff
@@ -440,17 +475,17 @@ impl PyStr {
...
-    #[track_caller] // <- can remove this once it doesn't panic
-    pub fn as_str(&self) -> &str {
-        self.data.as_str().expect("str has surrogates")
-    }
-
     pub fn to_str(&self) -> Option<&str> {
         self.data.as_str()
     }
 
+    /// Returns `&str`, panicking if the string contains surrogates.
```
Comment (ShaharNaveh) [inline crates/vm/src/builtins/str.rs]:
```suggestion
    /// Returns [`&str`].
    ///
    /// # Panic
    /// If the string contains surrogates.
```

File: crates/vm/src/builtins/function.rs (hunk 2 above)
Comment (youknowone) [reply crates/vm/src/builtins/function.rs:1079]: it was redundant
