### PR TITLE
Handle MemoryError for sequences

### LINKED ISSUE #1750: list panic when size > isize::MAX
## code
`[...] * (2 << 61)`

## result
`thread 'main' panicked at 'capacity overflow', src/liballoc/raw_vec.rs:777:5`

## expected result
an `MemoryError` exception

### PR DESCRIPTION
**Pull request by crazymerlyn**
Fixes #1750 

Based on #1779 which seems to be abandoned.

### CODE REVIEW

File: vm/src/vm/mod.rs [hunk 1]
```diff
@@ -53,6 +53,8 @@ pub use interpreter::Interpreter;
 pub(crate) use method::PyMethod;
 pub use setting::Settings;
 
+pub const MAX_MEMORY_SIZE: usize = (usize::MAX >> 3) + 1;
```
Comment (youknowone) [inline vm/src/vm/mod.rs:56]: Thank you! Is this constant came from CPython?

**Comment by youknowone** [comment]
Added @coolreader18 as a reviewer who reviewed #1779

File: vm/src/vm/mod.rs (hunk 1 above)
Comment (crazymerlyn) [reply vm/src/vm/mod.rs:56]: Nah, I just copied it from the last PR. CPython seems to use max usize instead: https://github.com/python/cpython/blob/e0a41a5dd12cb6e9277b05abebac5c70be684dd7/Objects/listobject.c#L740, https://github.com/python/cpython/blob/e0a41a5dd12cb6e9277b05abebac5c70be684dd7/Include/pyport.h#L146

Comment (coolreader18) [reply vm/src/vm/mod.rs:56]: That looks like `isize::MAX`, since the first s in `ssize_t` means signed. Which makes sense, since that's the max size an allocation can be for LLVM. I do think we could maybe just use `isize::MAX`, because otherwise we're unnecessarily constraining allocation size to "just" 512GiB on 32-bit systems.

Comment (crazymerlyn) [reply vm/src/vm/mod.rs]: Updated to use `isize::MAX`. Also updated to include the size of the type and fixed the potential integer overflow problem.

**Review by coolreader18 — APPROVED** [review]
LGTM, thanks for contributing!
