### PR TITLE
fix(sqlite): raise `ProgrammingError` when operating on a blob with a…

### LINKED ISSUE #6285: sqlite: Raise ProgrammingError when operating on a blob with a closed connection
Currently, the `sqlite3` module does not correctly handle cases where a `Blob` object is accessed after its parent database connection has been closed.

**Expected Behavior**
To match CPython's behavior, attempting to `read` (or perform other operations) on a blob after calling `connection.close()` should raise a `sqlite3.ProgrammingError` with the message "Cannot operate on a closed database".

**Context**
This issue prevents the standard library test `test_blob_closed_db_read` from passing. We need to add a check to ensure the connection is still open before processing blob operations.

### PR DESCRIPTION
**Pull request by ever0de**
… closed connection,

Fixed #6285

reference:
- https://github.com/python/cpython/blob/a8733cbc7328dbeeed50e82ef13abb197d511c46/Modules/_sqlite/connection.c#L699-L701
- https://github.com/python/cpython/blob/a8733cbc7328dbeeed50e82ef13abb197d511c46/Modules/_sqlite/blob.c#L70-L73
- https://github.com/python/cpython/blob/a8733cbc7328dbeeed50e82ef13abb197d511c46/Modules/_sqlite/blob.c#L183-L189

## Summary by CodeRabbit

* **New Features**
  * Added ability to check if a database connection is closed

* **Bug Fixes**
  * Database read operations now fail gracefully with error messaging when the connection is closed

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: crates/stdlib/src/sqlite.rs [hunk 1]
```diff
@@ -2169,6 +2173,13 @@ mod _sqlite {
             length: OptionalArg<c_int>,
             vm: &VirtualMachine,
         ) -> PyResult<PyRef<PyBytes>> {
+            if self.connection.is_closed() {
```
Comment (ShaharNaveh) [inline crates/stdlib/src/sqlite.rs:2176]: Can you please put the link in the PR here? it will be easier to access rather than going to git blame -> PR -> links

Comment (ever0de) [reply crates/stdlib/src/sqlite.rs:2176]: Could you please clarify the context? I am currently unable to understand why it's required.

Comment (ShaharNaveh) [reply crates/stdlib/src/sqlite.rs:2176]: Not required. Just my personal preference

Comment (youknowone) [reply crates/stdlib/src/sqlite.rs:2176]: This isn’t the official stance of our project, but I’d like to share my personal view on the matter.

If the behavior is something that’s common sense and easily predictable, I don’t think we need to attach a reference. In my opinion, this change falls into that category. Before adding this code, it might have been unclear whether such a check was necessary, but once the code is added, it becomes obvious that it is.

Some behaviors are hard to infer from the code alone. In those cases, having a reference linked is helpful. Depending on the situation, when pointing to the exact code is useful, we link specific line numbers; when it’s more important to refer to the conceptual location, we just mention the function name instead.

File: crates/stdlib/src/sqlite.rs [hunk 2]
```diff
@@ -2169,6 +2173,13 @@ mod _sqlite {
...
+                return Err(new_programming_error(
+                    vm,
+                    "Cannot operate on a closed database".to_owned(),
+                ));
+            }
```
[the remark this answers is not in the document]
Comment (youknowone) [reply crates/stdlib/src/sqlite.rs:2181]: @ever0de How do you think about this comment?

**Review by youknowone — APPROVED** [review]
Thanks!

File: crates/stdlib/src/sqlite.rs (hunk 2 above)
[the remark this answers is not in the document]
Comment (ever0de) [reply crates/stdlib/src/sqlite.rs:2181]: @youknowone Can I handle this in a separate issue?
