### PR TITLE
Fix global declaration error in the function

### LINKED ISSUE #1353: When call global twice for the same variable, SyntaxError occurs.
## Feature

```python
a = []
def f(b):
    global a
    global a  # Generate error only in RustPython
    a.append(b)
    print(a)

f(3)
print(a)
```
The code above generates the following error:
(when call global twice for the same variable, an error occurs.)
### Actual result
```bash
Hyeockz:RustPython hyeockjinkim$ cargo run e.py 
    Finished dev [unoptimized + debuginfo] target(s) in 0.11s
     Running `target/debug/rustpython e.py`
SyntaxError: name 'a' is used prior to global declaration at line 0 column 0
```
### Expected result
```bash
[3]
[3]
```

### PR DESCRIPTION
**Pull request by HyeockJinKim**
Fix Global symbol to prevent syntax error
when global declaration for same variable in function.

Fixes #1353

### CODE REVIEW

**Comment by HyeockJinKim** [comment]
@coolreader18 @youknowone cc @corona10 
Can I get a review?

File: compiler/src/symboltable.rs [hunk 1]
```diff
@@ -747,10 +747,13 @@ impl SymbolTableBuilder {
             // Role already set..
             match role {
                 SymbolUsage::Global => {
-                    return Err(SymbolTableError {
-                        error: format!("name '{}' is used prior to global declaration", name),
-                        location,
-                    })
+                    let symbol = table.symbols.get(name).unwrap();
+                    if symbol.is_assigned {
```
Comment (windelbouwman) [inline compiler/src/symboltable.rs]: How about this case:
```python
def foo():
    print(x)
    global x
```

In this case `x` is not assigned, but global is not allowed anyways.

Instead of `symbol.is_assigned`, check if `symbol.scope` is set to `Global` before.

Comment (HyeockJinKim) [reply compiler/src/symboltable.rs]: I think it is important that the variable is used or referenced in same scope rather than global declaration of variable, so I used `symbol.is_assigned` and `symbol.is_referenced`. Is my solution wrong?

Comment (windelbouwman) [reply compiler/src/symboltable.rs]: I think your solution is wrong, and the only legal re-declaration of a global is when the variable was previously marked as global, so in that case, check for `symbol.is_global`, this should be true, otherwise we face an error.

Comment (HyeockJinKim) [reply compiler/src/symboltable.rs]: Can I get a review again?
