### PR TITLE
Fixed #191, fixes recursive repr() for the standard collections

### LINKED ISSUE #191: Print circular objects causes stack overflow
```
>>>>> d = {}; d['d'] = d; d

thread 'main' has overflowed its stack
fatal runtime error: stack overflow
Aborted (core dumped)
```

Cpython:

```
>>> d = {}; d['d'] = d; d
{'d': {...}}
```

### PR DESCRIPTION
**Pull request by skinny121**
list/set/tuple and dict now use a guard to check for recursion. I change the tracing of frames to use debug of PyObjectRef instead of PyObject.str() as it caused stack overflows while creating the string to print.

### CODE REVIEW

File: vm/src/pyobject.rs [hunk 1]
```diff
@@ -1032,76 +1032,6 @@ impl PyObject {
         .into_ref()
     }
 
-    /// Deprecated method, please call `vm.to_pystr`
-    pub fn str(&self) -> String {
```
Comment (windelbouwman) [inline vm/src/pyobject.rs]: I am more than happy to see this go :)

File: vm/src/obj/objtuple.rs [hunk 2]
```diff
@@ -213,18 +213,22 @@ fn tuple_new(vm: &mut VirtualMachine, args: PyFuncArgs) -> PyResult {
 fn tuple_repr(vm: &mut VirtualMachine, args: PyFuncArgs) -> PyResult {
     arg_check!(vm, args, required = [(zelf, Some(vm.ctx.tuple_type()))]);
 
-    let elements = get_elements(zelf);
+    let s = if let Some(_guard) = ReprGuard::enter(zelf) {
```
Comment (windelbouwman) [inline vm/src/obj/objtuple.rs]: Is it possible to create a recursive tuple?

Comment (skinny121) [reply vm/src/obj/objtuple.rs]: Yes, tuple elements are still mutable so putting the tuple into one if it's elements. makes it recursive
