### PR TITLE
Fix panic

### LINKED ISSUE #5501: Panic in codecs.rs
Windows x86-64 debug build with default features when running `cargo run -- -m test`.

```
thread 'main' panicked at vm\src\codecs.rs:626:12:
attempt to subtract with overflow
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\rustpython.exe -m test` (exit code: 101)
```

### PR DESCRIPTION
**Pull request by arihant2math**
Fixes #5501

### CODE REVIEW

File: vm/src/codecs.rs [hunk 1]
```diff
@@ -623,7 +623,7 @@ fn surrogatepass_errors(err: PyObjectRef, vm: &VirtualMachine) -> PyResult<(PyOb
         // Try decoding a single surrogate character. If there are more,
         // let the codec call us again.
         let p = &s.as_bytes()[range.start..];
-        if p.len() - range.start >= byte_length {
+        if (p.len() as isize) - range.start as isize >= byte_length as isize {
```
Comment (youknowone) [inline vm/src/codecs.rs:626]:
```suggestion
        if p.len() >= range.start + byte_length {
```
How about this? is this also panic?

Comment (arihant2math) [reply vm/src/codecs.rs:626]: isize should not overflow downwards, I tested it and it fixed the issue.

Comment (youknowone) [reply vm/src/codecs.rs:626]: isize casting is usually not an issue on 64bit architecture but sometimes on 32bit one by limiting it half size. We can avoid it when possible. I will take current changes if removing subtraction doesn't fix problem.

Comment (arihant2math) [reply vm/src/codecs.rs:626]: I switched to saturating subtraction, hopefully that works as well.

**Comment by arihant2math** [comment]
I think it should be at a better solution at this point.

**Review by coolreader18 — APPROVED** [review]
LGTM
