### PR TITLE
Fix unicode decode bug on surrogate error mode

### LINKED ISSUE #5542: bytes.decode doesn't honor error mode
On Windows:
```
❯ python
Python 3.13.1 (tags/v3.13.1:0671451, Dec  3 2024, 19:06:28) [MSC v.1942 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> b'test_6868_tmp\xed\xb4\x80'.decode("utf-8", "surrogatepass")
'test_6868_tmp\udd00'
>>> exit()
❯ ./target/release/rustpython
Welcome to the magnificent Rust Python 0.4.0 interpreter 😱 🖖
RustPython 3.13.0
Type "help", "copyright", "credits" or "license" for more information.
>>>>> b'test_6868_tmp\xed\xb4\x80'.decode("utf-8", "surrogatepass")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "encodings_utf_8", line 16, in decode
UnicodeDecodeError: ('utf-8', b'test_6868_tmp\xed\xb4\x80', 13, 14, 'invalid continuation byte')
>>>>> exit()
```

The rustpython demo on the web also fails (although that is really out of date).

### PR DESCRIPTION
**Pull request by arihant2math**
Fixes #5542; error introduced by #5502. Adds some debug assertions that are also in cpython.
This will help allow test_argparse to work for windows.

### CODE REVIEW

File: vm/src/codecs.rs [hunk 1]
```diff
@@ -619,11 +619,16 @@ fn surrogatepass_errors(err: PyObjectRef, vm: &VirtualMachine) -> PyResult<(PyOb
...
+        debug_assert!(range.start <= 0.max(s.len() - 1));
+        debug_assert!(range.end >= 1.min(s.len()));
+        debug_assert!(range.end <= s.len());
+
         let mut c: u32 = 0;
         // Try decoding a single surrogate character. If there are more,
         // let the codec call us again.
         let p = &s.as_bytes()[range.start..];
-        if p.len().saturating_sub(range.start) >= byte_length {
+        if p.len().overflowing_sub(range.start).0 >= byte_length {
```
Comment (youknowone) [inline vm/src/codecs.rs:631]:
```suggestion
        if p.len() >= range.start + byte_length {
```
does this work?

Comment (arihant2math) [reply vm/src/codecs.rs]: It doesn't

Comment (youknowone) [reply vm/src/codecs.rs:631]: Thank you for confirming

**Review by youknowone — APPROVED** [review]
