### PR TITLE
Fixes `repr` of functions defined in classes

### LINKED ISSUE #2776: Invalid `repr` of methods
## Feature

CPython:

```python
>>> class A:
...    def some(self): ...
... 
>>> A.some
<function A.some at 0x1027e63a0>
```

RustPython:

```python
>>>>> class A:
.....    def some(self): ...
..... 
>>>>> A.some
<function some at 0x7fb7ae826e50>
```

### PR DESCRIPTION
**Pull request by sobolevn**
Closes #2776

### CODE REVIEW

**Review by youknowone — APPROVED** [review]
it looks good. will you fix the clippy error?

File: vm/src/builtins/function.rs [hunk 1]
```diff
@@ -352,8 +352,16 @@ impl PyFunction {
...
-    fn repr(zelf: PyRef<Self>) -> String {
-        format!("<function {} at {:#x}>", zelf.name.lock(), zelf.get_id())
+    fn repr(zelf: PyRef<Self>, vm: &VirtualMachine) -> String {
+        let attr: Option<PyStrRef> = vm
+            .get_attribute(zelf.as_object().clone(), "__qualname__")
+            .ok()
+            .and_then(|qualname_attr| qualname_attr.downcast().ok());
+        let qualname = attr
+            .map(|strref| strref.as_str().to_owned())
+            .unwrap_or(zelf.name.lock().as_str().to_owned());
```
Comment (DimitrisJim) [inline vm/src/builtins/function.rs:362]: Pretty sure this can be simplified to:

```suggestion
        let qualname = vm
            .get_attribute(zelf.as_object().clone(), "__qualname__")
            .ok()
            .and_then(|qualname_attr| qualname_attr.downcast::<PyStr>().ok())
            .unwrap_or_else(|| zelf.name()).as_str().to_owned();
```

@youknowone any better way to simplify here?

Comment (youknowone) [reply vm/src/builtins/function.rs:362]: it looks great, I think your version is the canonical one

Comment (youknowone) [reply vm/src/builtins/function.rs]: `use PyStr` is missed

**Comment by sobolevn** [comment]
Oh, GitHub is up again! 👍
